spring.application.name=veriskill-backend
server.port=9090

# Database (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/veriskill_db
spring.datasource.username=postgres
spring.datasource.password=Sittu#36
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


jwt.secret=veriskill_super_secret_key_change_this_in_production
jwt.expiration=86400000

ai.service.url=http://localhost:8000
